### ISSUE TITLE
希望出一个http1.x的

### ISSUE THREAD

**Issue by stonesinging** [cloudwego/netpoll-http2#12]
用netpoll接入项目时，目前还是自己手写的OnRequest处理接收http1.x的处理，如果有个能像netpoll-http2这种支持下1.x的http协议就好了

**Comment by SinnerA** [comment]
可以期待下 cloudwego 即将开源的 Hertz 框架，支持 h1 和 h2，预计开源时间在 6月

**Comment by stonesinging** [comment]
> 可以期待下 cloudwego 即将开源的 Hertz 框架，支持 h1 和 h2，预计开源时间在 6月

等很久了，只是老项目打算适配netpoll时没法完全用新框架，在可控范围内改造只能手动试着处理1.x，谁让net/http集成到了核心包里了呢，也没法直接改造net/http替换成netpoll
