### ISSUE TITLE
demo for h2 proxy

### ISSUE THREAD

**Issue by alonlong** [cloudwego/netpoll-http2#2]
can u help to provide a demo for building a h2 proxy with this library?

**Comment by SinnerA** [comment]
This is a http2 implementation based on netpoll, there is still a lot of work to do to implement a http2 proxy

**Comment by alonlong** [comment]
ok, Got it

**Comment by alonlong** [comment]
no, i mean h2 proxy

**Comment by 2391003262** [comment]
http3 is faster than http2. I think this is not must work for implement that.

**Comment by GuangmingLuo** [comment]
Sorry, this repo will be archived
